
// All basic fs structures declared HERE

// EXT2FS
pub const Superblock = extern struct {
    inodes_count: u32,
    blocks_count: u32,
    r_blocks_count: u32,
    free_blocks_count: u32,
    free_inodes_count: u32,
    first_data_block: u32,
    log_block_size: u32,
    log_frag_size: u32,
    blocks_per_group: u32,
    frags_per_group: u32,
    inodes_per_group: u32,
    mtime: u32,
    wtime: u32,
    mnt_count: u16,
    max_mnt_count: u16,
    magic: u16,
    state: u16,
    errors: u16,
    minor_rev_level: u16,
    lastcheck: u32,
    checkinterval: u32,
    os_id: u32,
    rev_level: u32,
    def_resuid: u16,
    def_resgid: u16,
    first_ino: u32,
    inode_size: u16,
    block_group_nr: u16,
    feature_compat: u32,
    feature_incompat: u32,
    feature_ro_compat: u32,
    uuid: [16]u8,
    volume_name: [16]u8,
    last_mounted: [64]u8,
    algo_bitmap: u32,
    prealloc_blocks: u8,
    prealloc_dir_blocks: u8,
    alignment1: u16,
    journal_uuid: [16]u8,
    journal_inum: u32,
    journal_dev: u32,
    last_orphan: u32,
    hash_seed: [4]u32,
    def_hash_version: u8,
    padding1: [3]u8,
    default_mount_options: u32,
    first_meta_bg: u32,
    reserved: [760]u8,
};

pub const Block_Group_Descriptor = extern struct {
    block_bitmap: u32,
    inode_bitmap: u32,
    inode_table: u32,
    free_blocks_count: u16,
    free_inodes_count: u16,
    used_dirs_count: u16,
    pad: u16,
    reserved: [14]u8,
};

pub const Inode = extern struct {
    mode: u16,
    uid: u16,
    size: u32,
    atime: u32,
    ctime: u32,
    mtime: u32,
    dtime: u32,
    gid: u16,
    links_count: u16,
    blocks: u32,
    flags: u32,
    osd1: u32,
    block0: u32,
    block1: u32,
    block2: u32,
    block3: u32,
    block4: u32,
    block5: u32,
    block6: u32,
    block7: u32,
    block8: u32,
    block9: u32,
    block10: u32,
    block11: u32,
    singly_block: u32,
    doubly_block: u32,
    triply_block: u32,
    generation: u32,
    file_acl: u32,
    dir_acl: u32,
    faddr: u32,
    osd2: [12]u8,
};

pub const Directory_Entry = extern struct {
    inode: u32,
    size: u16,
    name_len: u8,
    type_id: u8,
    name: [256]u8,
};


// FAT12
pub const BPB = packed struct {
    jmp_boot: u24,
    oem_name: u64,
    bytes_per_sector: u16,
    sectors_per_cluster: u8,
    reserved_sector_count: u16,
    fat_numbers: u8,
    root_entry_count: u16,
    sectors_total: u16,
    media: u8,
    sectors_per_fat: u16,
    sectors_per_track: u16,
    heads: u16,
    hidden_sectors: u32,
    expanded_sectors_total: u32,
    // extended boot record:
    drive_number: u8,
    winnt_flags: u8,
    signature0: u8,
    volume_id: u32,
    volume_label_string: u88,
    sys_id: u64,
    boot_code: u3584,
    signature1: u16,
};

pub const FAT12_Directory_Entry = extern struct {
    file_name: [8]u8,
    file_ext: [3]u8,
    file_flags: u8,
    reserved: u8,
    creation_time0: u8,
    creation_time1: u16,
    creation_date: u16,
    last_accessed: u16,
    cluster_num: u16,
    last_modified_time: u16,
    last_modified_date: u16,
    first_cluster: u16,
    file_size: u32,
};


