// All basic fs structures declared HERE

const Superblock = struct {
    inodes: u32,
    blocks: u32,
    reserved: u32,
    blocks_free: u32,
    inodes_free: u32,
    superblock_block: u32,
    log2_blocksize: u32,
    log2_fragmentsize: u32,
    blocks_pergroup: u32,
    fragments_pergroup: u32,
    inodes_pergroup: u32,
    last_mount: u32,
    last_write: u32,
    mount_since: u16,
    mount_before: u16,
    ext2: u16,
    fs_state: u16,
    error_handling: u16,
    minor_portion: u16,
    last_cons_check: u32,
    interval_cons_check: u32,
    os_id: u32,
    major_portion: u32,
    reserved_user_id: u16,
    reserved_group_id: u16,
};
